# Generated by Django 4.2.6 on 2023-10-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, default='company description goes here....', null=True)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT')], max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
